import test, { mock } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, chmod, rm, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { loadJob, runSecretName, cloudRunToken, crc32c } from '../dist/jobs/job-config.js';
const require=createRequire(new URL('../dist/job.js',import.meta.url));
const {SecretManagerServiceClient}=require('@google-cloud/secret-manager');
const uuid='7a5b6f5e-4b7d-4af7-8f30-9de2a744ce87';const site='fixture-site';const token='dummy-run-token'.padEnd(43,'A');
async function setup(t,cloud=false){const directory=await mkdtemp(join(tmpdir(),'odvr-job-'));t.after(()=>rm(directory,{recursive:true,force:true}));const config=join(directory,'registration.json');const registration={schema_version:1,profile:cloud ? 'cloud':'local',sites:{[site]:{callback_base:'https://control.test/wp-json/odvr/v1/runner'}},...(cloud ? {secret_project:'123456789012'}:{local_secret_directory:directory,local_destination:{origin:'https://control.test',address:'192.168.1.2',port:443}})};await writeFile(config,JSON.stringify(registration),{mode:0o600});const name=runSecretName(site,uuid);const file=join(directory,name);await writeFile(file,token,{mode:0o600});const resource=`projects/123456789012/secrets/${name}/versions/1`;const environment={ODVR_JOB_CONFIG:config,ODVR_SITE_ID:site,ODVR_RUN_UUID:uuid,ODVR_TOKEN_EXPIRES_AT:new Date(Date.now()+60000).toISOString(),...(cloud ? {CLOUD_RUN_EXECUTION:'execution',CLOUD_RUN_TASK_COUNT:'1',CLOUD_RUN_TASK_INDEX:'0',ODVR_RUN_SECRET_VERSION:resource}:{ODVR_LOCAL_EXECUTION_ID:'execution'})};return {directory,config,file,registration,environment,resource};}
test('ローカル秘密は固定名の0600ファイルだけから取得し引数を使わない',async t=>{const {environment,file}=await setup(t);const job=await loadJob(environment);assert.equal(job.client.token,token);assert.equal(job.client.executionId,'execution');await chmod(file,0o644);await assert.rejects(loadJob(environment));});
test('秘密/登録設定のsymlink・書込可能設定・別site・期限超過を拒否する',async t=>{const {environment,file,config,directory}=await setup(t);await assert.rejects(loadJob({...environment,ODVR_SITE_ID:'other'}));await assert.rejects(loadJob({...environment,ODVR_CALLBACK_BASE:'https://other.test/wp-json/odvr/v1/runner'}));await assert.rejects(loadJob({...environment,ODVR_TOKEN_EXPIRES_AT:new Date(Date.now()-1000).toISOString()}));await assert.rejects(loadJob({...environment,ODVR_TOKEN_EXPIRES_AT:new Date(Date.now()+7200000).toISOString()}));await assert.rejects(loadJob({...environment,CLOUD_RUN_JOB:'cloud'}));await chmod(config,0o622);await assert.rejects(loadJob(environment));await chmod(config,0o600);const other=join(directory,'other');await writeFile(other,token,{mode:0o600});await rm(file);await symlink(other,file);await assert.rejects(loadJob(environment));});
test('cloud秘密は登録project/site/UUIDの数値versionだけを読みTask数を固定する',async t=>{const {environment,resource}=await setup(t,true);let reads=0;const reader=async name=>{reads++;assert.equal(name,resource);return token;};const job=await loadJob(environment,reader);assert.equal(job.client.token,token);assert.equal(reads,1);for(const changed of [{CLOUD_RUN_TASK_COUNT:'2'},{CLOUD_RUN_TASK_INDEX:'1'},{ODVR_RUN_SECRET_VERSION:resource.replace('/versions/1','/versions/latest')},{ODVR_RUN_SECRET_VERSION:resource.replace('123456789012','999999999999')},{ODVR_RUN_SECRET_VERSION:resource.replace(uuid,'different')},{GOOGLE_APPLICATION_CREDENTIALS:'private.json'},{GOOGLE_SDK_NODE_LOGGING:'all'}])await assert.rejects(loadJob({...environment,...changed},reader));assert.equal(reads,1);});
test('Google adapterは固定endpoint・timeout・retryなし・CRC32Cを検査し原文を隠す',async t=>{const resource='projects/123456789012/secrets/fixed/versions/1';assert.equal(crc32c(Buffer.from('123456789')),0xe3069283);let mode='healthy';let closed=0;const access=mock.method(SecretManagerServiceClient.prototype,'accessSecretVersion',async function(input,options){assert.equal(this.apiEndpoint,'secretmanager.googleapis.com');assert.equal(input.name,resource);assert.equal(options.timeout,10000);assert.equal(options.retry,null);if(mode==='error')throw new Error(`Bearer ${token} ${resource}`);return [{name:resource,payload:{data:Buffer.from(token),dataCrc32c:String(crc32c(Buffer.from(token))+(mode==='bad' ? 1:0))}}];});const close=mock.method(SecretManagerServiceClient.prototype,'close',async()=>{closed++;});t.after(()=>{access.mock.restore();close.mock.restore();});assert.equal(await cloudRunToken(resource),token);for(mode of ['bad','error'])await assert.rejects(cloudRunToken(resource),error=>!error.message.includes(token) && !error.message.includes(resource));assert.equal(closed,3);});
test('Job CLIは追加引数/SDK/設定例外の原文と秘密参照をログへ出さない',()=>{const resource='projects/private-project/secrets/private/versions/1';for(const args of [[token],[]]){const result=spawnSync(process.execPath,['apps/runner/dist/job.js',...args],{encoding:'utf8',env:{...process.env,ODVR_JOB_CONFIG:'/missing',ODVR_RUN_SECRET_VERSION:resource}});assert.equal(result.status,1);assert.match(result.stderr,/ODVR_JOB_FAILED/);assert.ok(!result.stderr.includes(token));assert.ok(!result.stderr.includes(resource));assert.ok(!result.stderr.includes('/missing'));}});
