import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtemp,writeFile,readFile,rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { checkedLocalEntry,queueFilename } from '../dist/jobs/local-queue.js';
import { runSecretName } from '../dist/jobs/job-config.js';
import { processEntry,runTask } from '../../../infra/local/launcher.mjs';
async function setup(t){const root=await mkdtemp(join(tmpdir(),'odvr-launch-'));t.after(()=>rm(root,{recursive:true,force:true}));const run=randomUUID();const attempt=randomUUID();const name='projects/odvr-local/locations/asia-northeast1/jobs/runner';const config={job:{name,image:'odvr/runner@sha256:'+'1'.repeat(64),generation:'1'},secret_project:'222222222222',sites:{fixture:{callback_base:'https://wordpress.fixture.test:8443/wp-json/odvr/v1/runner'}}};const entry={storage_version:1,operation:name.split('/jobs/')[0]+'/operations/'+attempt,execution:{name:name+'/executions/local-'+attempt,created_at:Date.now(),terminal:false,image:config.job.image,environment:{ODVR_SITE_ID:'fixture',ODVR_RUN_UUID:run,ODVR_CALLBACK_BASE:config.sites.fixture.callback_base,ODVR_RUN_SECRET_VERSION:'projects/'+config.secret_project+'/secrets/'+runSecretName('fixture',run)+'/versions/1',ODVR_ATTEMPT_ID:attempt,ODVR_TOKEN_EXPIRES_AT:new Date(Date.now()+60000).toISOString()}},state:'queued',attempts:0,job_generation:'1',task_started_at:null};const path=join(root,queueFilename(entry.operation));await writeFile(path,JSON.stringify(entry),{mode:0o600});return {root,config,entry,path};}
test('有限launcherは固定Executionのまま初回とretry1だけを実行する',async t=>{const c=await setup(t);const observed=[];await processEntry(c.path,c.config,new AbortController().signal,async entry=>{observed.push(structuredClone(entry));assert.equal(JSON.parse(await readFile(c.path,'utf8')).attempts,observed.length);return 1;});assert.equal(observed.length,2);assert.equal(observed[0].execution.name,observed[1].execution.name);const completed=JSON.parse(await readFile(c.path,'utf8'));assert.equal(completed.state,'terminal');assert.equal(completed.attempts,2);assert.equal(completed.execution.terminal,true);await processEntry(c.path,c.config,new AbortController().signal,async()=>assert.fail('3回目を起動した'));});
test('起動marker後のrestartは2回目だけを使い、2回目のrestartは起動しない',async t=>{const c=await setup(t);c.entry.state='running';c.entry.attempts=1;c.entry.task_started_at=Date.now();await writeFile(c.path,JSON.stringify(c.entry));let runs=0;await processEntry(c.path,c.config,new AbortController().signal,async entry=>{runs++;assert.equal(entry.attempts,2);return 0;});assert.equal(runs,1);c.entry.attempts=2;await writeFile(c.path,JSON.stringify(c.entry));await processEntry(c.path,c.config,new AbortController().signal,async()=>assert.fail('3回目を起動した'));assert.equal(JSON.parse(await readFile(c.path,'utf8')).state,'terminal');});
test('期限切れは起動せず、偽造env・別digest・任意commandを拒否する',async t=>{const c=await setup(t);c.entry.execution.environment.ODVR_TOKEN_EXPIRES_AT=new Date(Date.now()-1000).toISOString();await writeFile(c.path,JSON.stringify(c.entry));await processEntry(c.path,c.config,new AbortController().signal,async()=>assert.fail('期限後に起動した'));assert.equal(JSON.parse(await readFile(c.path,'utf8')).state,'terminal');for(const mutate of [v=>v.execution.environment.TOKEN='dummy',v=>v.execution.image='image:latest',v=>v.command='arbitrary',v=>v.execution.environment.ODVR_CALLBACK_BASE='https://other.test',v=>v.execution.environment.ODVR_RUN_SECRET_VERSION=v.execution.environment.ODVR_RUN_SECRET_VERSION.replace('/versions/1','/versions/latest')]){const entry=structuredClone(c.entry);mutate(entry);assert.throws(()=>checkedLocalEntry(entry,c.config,c.path.split('/').at(-1)));}});
test('子Runnerには固定入口と非秘密値だけを渡し、Task timeoutで終了する',async t=>{const {EventEmitter}=await import('node:events');const c=await setup(t);const entry={...c.entry,task_started_at:Date.now()-1800000+10};let commands;let killed=false;const spawn=(command,args,options)=>{commands={command,args,options};const child=new EventEmitter();child.kill=signal=>{killed=true;assert.ok(['SIGTERM','SIGKILL'].includes(signal));if(signal==='SIGTERM')child.emit('exit',null);};return child;};assert.equal(await runTask(entry,new AbortController().signal,spawn),1);assert.equal(killed,true);assert.deepEqual(commands.args,['apps/runner/dist/job.js']);assert.equal(commands.options.env.ODVR_LOCAL_EXECUTION_ID,entry.execution.name.split('/').at(-1));assert.equal(commands.options.env.ODVR_RUN_SECRET_VERSION,undefined);assert.equal(commands.options.env.ODVR_RUN_TOKEN,undefined);assert.equal(commands.options.env.GOOGLE_APPLICATION_CREDENTIALS,undefined);});

test('Image更新後の終了済み履歴は再起動せず、未終了の別digestは拒否する',async t=>{const c=await setup(t);c.entry.execution.image='odvr/runner@sha256:'+'2'.repeat(64);assert.throws(()=>checkedLocalEntry(c.entry,c.config,c.path.split('/').at(-1),true));c.entry.state='terminal';c.entry.attempts=1;c.entry.task_started_at=Date.now();c.entry.execution.terminal=true;await writeFile(c.path,JSON.stringify(c.entry));await processEntry(c.path,c.config,new AbortController().signal,async()=>assert.fail('終了済み履歴を起動した'));});
