import { createHash } from 'node:crypto';
import { isAbsolute,join } from 'node:path';
import { readPrivateFile } from '@odvr/runner/jobs/job-config';
import { open,readdir,lstat } from 'node:fs/promises';
import type { Acceptance,ExecutionInfo,JobLauncher } from './types.js';
import { DispatchError } from './types.js';
import type { DispatcherConfig } from './config.js';
import { jobEnvironment } from './google-jobs.js';
export interface LocalQueueEntry {storage_version:1;operation:string;execution:ExecutionInfo;state:'queued'|'running'|'terminal';attempts:number;job_generation:string}
/** local launcherへ固定メタデータだけを永続受け渡しする。起動は#38の有限launcherが担当する。 */
export class LocalJobQueue implements JobLauncher {
  readonly directory:string;
  constructor(readonly config:DispatcherConfig,readonly clock=Date.now){if(config.profile!=='local' || !config.local || !isAbsolute(config.local.queue_directory) || process.env.K_SERVICE || process.env.CLOUD_RUN_JOB || process.env.CLOUD_RUN_EXECUTION)throw new Error('local Job queueの設定を確認してください。');this.directory=config.local.queue_directory;}
  #file(name:string):string{return join(this.directory,createHash('sha256').update(name).digest('hex')+'.json');}
  async #read(path:string):Promise<LocalQueueEntry>{const entry=JSON.parse((await readPrivateFile(path,16384,true)).toString('utf8')) as LocalQueueEntry;const value=entry.execution;const prefix=this.config.job.name+'/executions/';if(Object.keys(entry).sort().join()!=='attempts,execution,job_generation,operation,state,storage_version' || entry.storage_version!==1 || !['queued','running','terminal'].includes(entry.state) || !Number.isInteger(entry.attempts) || entry.attempts<0 || entry.attempts>2 || entry.job_generation!==this.config.job.generation || !value || Object.keys(value).sort().join()!=='created_at,environment,image,name,terminal' || !value.name.startsWith(prefix) || !/^local-[a-f0-9-]{36}$/.test(value.name.slice(prefix.length)) || !Number.isSafeInteger(value.created_at) || typeof value.terminal!=='boolean' || value.terminal!==(entry.state==='terminal') || value.image!==this.config.job.image || !value.environment || Object.keys(value.environment).sort().join()!=='ODVR_ATTEMPT_ID,ODVR_CALLBACK_BASE,ODVR_RUN_SECRET_VERSION,ODVR_RUN_UUID,ODVR_SITE_ID,ODVR_TOKEN_EXPIRES_AT' || !Object.values(value.environment).every(item=>typeof item==='string' && item.length<=2048) || entry.operation!==this.config.job.name.split('/jobs/')[0]+'/operations/'+value.environment.ODVR_ATTEMPT_ID || this.#file(entry.operation)!==path)throw new DispatchError('odvr_queue_unavailable',503,true);return entry;}
  async #entries():Promise<LocalQueueEntry[]>{const files=(await readdir(this.directory)).filter(file=>/^[a-f0-9]{64}\.json$/.test(file));if(files.length>10000)throw new DispatchError('odvr_queue_unavailable',503,true);return Promise.all(files.map(async file=>this.#read(join(this.directory,file))));}
  async verify(record?:Acceptance):Promise<boolean>{const directory=await lstat(this.directory);return directory.isDirectory() && !(directory.mode&0o077) && (!record || (record.image===this.config.job.image && record.job_generation===this.config.job.generation));}
  async launch(record:Acceptance):Promise<string>{if(!record.attempt_id)throw new DispatchError('odvr_invalid_ledger',503,false);const operation=this.config.job.name.split('/jobs/')[0]+'/operations/'+record.attempt_id;const execution:ExecutionInfo={name:this.config.job.name+'/executions/local-'+record.attempt_id,created_at:this.clock(),terminal:false,image:record.image,environment:jobEnvironment(this.config,record)};const entry:LocalQueueEntry={storage_version:1,operation,execution,state:'queued',attempts:0,job_generation:record.job_generation};const file=await open(this.#file(operation),'wx',0o600);try{await file.writeFile(JSON.stringify(entry));await file.sync();}finally{await file.close();}return operation;}
  async operation(name:string):Promise<{execution:ExecutionInfo|null;failed:boolean}>{if(!name.startsWith(this.config.job.name.split('/jobs/')[0]+'/operations/'))throw new DispatchError('odvr_operation_mismatch',503,false);try{const entry=await this.#read(this.#file(name));if(entry.operation!==name)throw new DispatchError('odvr_operation_mismatch',503,false);return {execution:entry.state==='queued' ? null:entry.execution,failed:false};}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return {execution:null,failed:false};throw error;}}
  async execution(name:string):Promise<ExecutionInfo>{if(!name.startsWith(this.config.job.name+'/executions/'))throw new DispatchError('odvr_execution_mismatch',503,false);const entries=await this.#entries();const entry=entries.find(item=>item.execution.name===name);if(!entry)throw new DispatchError('odvr_execution_list_unavailable',503,true);return entry.execution;}
  async candidates(record:Acceptance):Promise<ExecutionInfo[]>{return (await this.#entries()).filter(item=>item.state!=='queued').map(item=>item.execution).filter(execution=>execution.created_at>=record.created_at-300000 && execution.created_at<=record.created_at+900000);}
  async close():Promise<void>{}
}
