import { createHash,randomUUID } from 'node:crypto';
import { isAbsolute,join } from 'node:path';
import { open,readFile,rename,rm,readdir,lstat } from 'node:fs/promises';
import { runSecretName,readPrivateFile } from '@odvr/runner/jobs/job-config';
import type { DispatcherConfig } from './config.js';
import type { Acceptance,SecretStore,SecretMetadata } from './types.js';
import { DispatchError } from './types.js';
import { labels,metadataMatches } from './google-secrets.js';
type Metadata=SecretMetadata & {granted:boolean};
/** localの専用tmpfsだけにダミー秘密を保持する。クラウドでは構築しない。 */
export class LocalSecretStore implements SecretStore {
  readonly #directory:string;
  constructor(readonly config:DispatcherConfig,readonly clock=Date.now){if(config.profile!=='local' || !config.local || !isAbsolute(config.local.run_directory) || !isAbsolute(config.local.shared_directory) || process.env.K_SERVICE || process.env.CLOUD_RUN_JOB || process.env.CLOUD_RUN_EXECUTION)throw new Error('local秘密adapterの設定を確認してください。');this.#directory=config.local.run_directory;}
  #path(record:Acceptance):string{return join(this.#directory,runSecretName(record.site_id,record.run_uuid));}
  #name(record:Acceptance):string{return `projects/${this.config.secret_project}/secrets/${runSecretName(record.site_id,record.run_uuid)}`;}
  async #metadata(path:string):Promise<Metadata|null>{try{return JSON.parse((await readPrivateFile(path,16384,true)).toString('utf8'));}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return null;throw error;}}
  async #write(path:string,value:object):Promise<void>{const temporary=path+'.'+randomUUID()+'.tmp';try{const file=await open(temporary,'wx',0o600);try{await file.writeFile(JSON.stringify(value));await file.sync();}finally{await file.close();}await rename(temporary,path);}finally{await rm(temporary,{force:true});}}
  async shared(resource:string):Promise<Buffer>{if(!Object.values(this.config.sites).some(site=>site.shared_versions.includes(resource)))throw new DispatchError('odvr_dispatch_unavailable',503,true);return readPrivateFile(join(this.config.local!.shared_directory,createHash('sha256').update(resource).digest('hex')),4096,true);}
  async create(record:Acceptance):Promise<void>{const path=this.#path(record)+'.metadata';if(await this.#metadata(path))return;if(record.expires_at-this.clock()<60000)throw new DispatchError('odvr_dispatch_expired',503,false);await this.#write(path,{name:this.#name(record),expires_at:record.expires_at,labels:labels(record),granted:false});}
  async inspect(record:Acceptance):Promise<SecretMetadata|null>{const metadata=await this.#metadata(this.#path(record)+'.metadata');if(metadata && metadata.name!==this.#name(record))throw new DispatchError('odvr_secret_ownership_conflict',503,false);return metadata;}
  async versions(record:Acceptance):Promise<string[]>{const metadata=await this.inspect(record);if(!metadata || !metadataMatches(record,metadata))throw new DispatchError('odvr_secret_ownership_conflict',503,false);try{const file=await lstat(this.#path(record));if(!file.isFile() || file.size!==43 || (file.mode&0o077))throw new DispatchError('odvr_secret_ownership_conflict',503,false);return [this.#name(record)+'/versions/1'];}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return [];throw error;}}
  async add(record:Acceptance,token:string):Promise<string>{const metadata=await this.inspect(record);if(!metadata || !metadataMatches(record,metadata) || !/^[A-Za-z0-9_-]{43}$/.test(token))throw new DispatchError('odvr_secret_ownership_conflict',503,false);const file=await open(this.#path(record),'wx',0o600);const bytes=Buffer.from(token);try{await file.writeFile(bytes);await file.sync();}finally{bytes.fill(0);await file.close();}return this.#name(record)+'/versions/1';}
  async grant(record:Acceptance):Promise<void>{const metadata=await this.inspect(record);if(!metadata || !metadataMatches(record,metadata) || !(await this.versions(record)).includes(record.secret_version ?? ''))throw new DispatchError('odvr_secret_ownership_conflict',503,false);await this.#write(this.#path(record)+'.metadata',{...metadata,granted:true});}
  async remove(record:Acceptance):Promise<void>{const metadata=await this.inspect(record);if(!metadata)return;if(!metadataMatches(record,metadata))throw new DispatchError('odvr_secret_ownership_conflict',503,false);await rm(this.#path(record),{force:true});await rm(this.#path(record)+'.metadata',{force:true});}
  async orphans(cursor:string|null,limit:number):Promise<{secrets:SecretMetadata[];cursor:string|null}>{const files=(await readdir(this.#directory)).filter(file=>/^odvr-run-[a-f0-9]{24}-[a-f0-9-]{36}\.metadata$/.test(file) && (!cursor || file>cursor)).sort().slice(0,limit);const secrets:SecretMetadata[]=[];for(const file of files){const metadata=await this.#metadata(join(this.#directory,file));if(metadata)secrets.push(metadata);}return {secrets,cursor:files.length===limit ? files.at(-1)!:null};}
  async removeOrphan(secret:SecretMetadata):Promise<void>{const site=secret.labels.site_sha;const uuid=secret.labels.run_uuid;const filename=`odvr-run-${site}-${uuid}`;if(secret.expires_at>this.clock() || secret.labels.odvr_owner!=='dispatcher-v1' || !/^[a-f0-9]{24}$/.test(site ?? '') || !/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(uuid ?? '') || secret.name!==`projects/${this.config.secret_project}/secrets/${filename}`)throw new DispatchError('odvr_secret_ownership_conflict',503,false);const current=await this.#metadata(join(this.#directory,filename+'.metadata'));if(!current)return;if(current.name!==secret.name || current.expires_at!==secret.expires_at || !Object.entries(secret.labels).every(([key,value])=>current.labels[key]===value))throw new DispatchError('odvr_secret_ownership_conflict',503,false);await rm(join(this.#directory,filename),{force:true});await rm(join(this.#directory,filename+'.metadata'),{force:true});}
  async close():Promise<void>{}
}
