import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile,writeFile,readdir,rm } from 'node:fs/promises';
import { join } from 'node:path';
import { context,token } from './fixtures/context.mjs';
import { DispatchEngine } from '../dist/engine.js';
import { LaunchRejected } from '../dist/types.js';
const accept=c=>c.engine.accept(c.input,c.body,c.clock());
async function terminal(c){const file=join(c.config.local.queue_directory,(await readdir(c.config.local.queue_directory))[0]);const value=JSON.parse(await readFile(file,'utf8'));value.state='terminal';value.attempts=2;value.execution.terminal=true;await writeFile(file,JSON.stringify(value));}
test('同時受付・異なる署名時刻での再送・restartでも起動とSecret versionは一つ',async t=>{const c=await context(t);const results=await Promise.all(Array.from({length:3},()=>accept(c).catch(error=>error)));assert.ok(results.some(result=>result.status===200));const record=await c.record();assert.equal(record.status,'started');assert.equal(record.secret_step,'ready');assert.equal((await readdir(c.config.local.queue_directory)).length,1);c.advance(1000);const restarted=await c.restart().accept(c.input,c.body,c.clock());assert.equal(restarted.body.runner_execution_id,record.execution.split('/').at(-1));assert.equal((await c.record()).expires_at,record.expires_at);assert.equal((await c.secrets.versions(record)).length,1);assert.ok(!(await readFile(join(c.root,'ledger','ledger.json'),'utf8')).includes(token));const queue=await readFile(join(c.config.local.queue_directory,(await readdir(c.config.local.queue_directory))[0]),'utf8');assert.ok(!queue.includes(token));assert.ok(!queue.includes('runner_token'));});
for(const phase of ['before_secret_create','after_secret_create','before_secret_version','after_secret_version','after_secret_grant','accepted','operation_saved','before_reply'])test('永続境界 '+phase+' の停止後に新しいworkerで復旧する',async t=>{const c=await context(t);c.engine.dependencies.fault=async current=>{if(current===phase)throw new Error('fixture interruption');};await assert.rejects(accept(c));c.advance(60001);await c.restart().worker();const record=await c.record();if(['before_secret_create','after_secret_create','before_secret_version'].includes(phase)){assert.equal(record.status,'failed');c.advance(60001);await c.restart().worker();assert.equal((await c.record()).secret_deleted,true);}else {if(record.status==='launch_unknown'){for(const name of await readdir(c.config.local.queue_directory)){const path=join(c.config.local.queue_directory,name);const entry=JSON.parse(await readFile(path,'utf8'));entry.state='running';entry.attempts=1;entry.task_started_at=entry.execution.created_at;await writeFile(path,JSON.stringify(entry));}c.advance(60001);await c.restart().worker();}assert.equal((await c.record()).status,'started');}assert.ok((await readdir(c.config.local.queue_directory)).length<=1);});
test('RunJob応答だけが失われてもExecutionを照合し再POSTしない',async t=>{const c=await context(t);const original=c.jobs.launch.bind(c.jobs);let calls=0;c.jobs.launch=async record=>{calls++;await original(record);throw new Error('response lost '+token);};const result=await accept(c);assert.equal(result.status,200);assert.equal(calls,1);c.advance(60001);await c.restart().worker();assert.equal((await c.record()).status,'started');assert.equal((await readdir(c.config.local.queue_directory)).length,1);});
test('起動前markerで停止し候補0なら期限まで不明のまま再起動しない',async t=>{const c=await context(t);c.engine.dependencies.fault=async phase=>{if(phase==='launching')throw new Error('crash');};await assert.rejects(accept(c));c.advance(60001);const engine=c.restart();await engine.worker();assert.equal((await c.record()).status,'launch_unknown');assert.equal((await readdir(c.config.local.queue_directory)).length,0);for(let i=0;i<3;i++){c.advance(60001);await engine.worker();}assert.equal((await readdir(c.config.local.queue_directory)).length,0);c.advance(5400000);await engine.worker();assert.equal((await c.record()).status,'failed');assert.equal((await c.record()).secret_deleted,true);});
test('候補が複数なら固定できず、別Run・image・attemptは一致させない',async t=>{const c=await context(t);const original=c.jobs.launch.bind(c.jobs);c.jobs.launch=async record=>{await original(record);throw new Error('lost');};c.jobs.candidates=async record=>{const value=(await new (c.jobs.constructor)(c.config,c.clock).candidates(record))[0];return [value,{...value,name:value.name+'-duplicate'}];};assert.equal((await accept(c)).status,202);assert.equal((await c.record()).error_code,'odvr_execution_ambiguous');c.advance(60001);c.jobs.candidates=async record=>{const value=(await new (c.jobs.constructor)(c.config,c.clock).candidates(record))[0];return [{...value,image:'different'},{...value,environment:{...value.environment,ODVR_RUN_UUID:'different'}},{...value,environment:{...value.environment,ODVR_ATTEMPT_ID:'different'}}];};await c.engine.worker();assert.equal((await c.record()).status,'launch_unknown');assert.equal((await readdir(c.config.local.queue_directory)).length,1);});
test('Task retryを含むExecution終端まで秘密を保持し削除失敗は再試行する',async t=>{const c=await context(t);await accept(c);const record=await c.record();assert.ok(await c.secrets.inspect(record));c.advance(60001);await c.restart().worker();assert.equal((await c.record()).secret_deleted,false);await terminal(c);const original=c.secrets.remove.bind(c.secrets);let deletes=0;c.secrets.remove=async record=>{deletes++;if(deletes===1)throw new Error(token);return original(record);};c.advance(60001);await c.engine.worker();assert.equal((await c.record()).active,false);assert.equal((await c.record()).secret_deleted,false);assert.equal((await c.record()).error_code,'odvr_cleanup_unavailable');c.advance(60001);await c.engine.worker();assert.equal((await c.record()).secret_deleted,true);assert.equal(deletes,2);assert.equal(await c.secrets.inspect(record),null);});
test('確実な起動拒否は失敗とし、所有権が違うSecretは削除しない',async t=>{const c=await context(t);c.jobs.launch=async()=>{throw new LaunchRejected();};await assert.rejects(accept(c),{status:503,retryable:false});assert.equal((await c.record()).secret_deleted,true);const other={...(await c.record()),run_uuid:'1d2d58e9-6fda-4a5b-9957-6c0c49895d27',expires_at:c.clock()+600000};await c.secrets.create(other);const metadata=await c.secrets.inspect(other);await assert.rejects(c.secrets.remove({...other,digest:'f'.repeat(64)}),{code:'odvr_secret_ownership_conflict'});await assert.rejects(c.secrets.removeOrphan({...metadata,labels:{...metadata.labels,odvr_owner:'another'}}));assert.ok(await c.secrets.inspect(other));c.advance(600001);assert.equal((await c.engine.worker()).deleted,1);assert.equal(await c.secrets.inspect(other),null);});
test('固定Job世代が変わった受付は起動せず10分後に回収する',async t=>{const c=await context(t);c.jobs.verify=async()=>false;assert.equal((await accept(c)).status,202);assert.equal((await c.record()).status,'accepted');c.advance(600001);await c.engine.worker();assert.equal((await c.record()).status,'failed');assert.equal((await readdir(c.config.local.queue_directory)).length,0);});
for(const phase of ['launching','after_job_run'])test('独立プロセスを '+phase+' で強制終了しても再起動しない',async t=>{const {spawn}=await import('node:child_process');const c=await context(t);const result=await new Promise((resolve,reject)=>{const child=spawn(process.execPath,['apps/dispatcher/tests/fixtures/crash-worker.mjs'],{stdio:['pipe','pipe','pipe']});let output='';child.stdout.on('data',chunk=>{output+=chunk;});child.stderr.on('data',chunk=>{output+=chunk;});child.on('error',reject);child.on('exit',code=>resolve({code,output}));child.stdin.end(JSON.stringify({config:c.config,root:c.root,body:c.body.toString('base64'),now:c.clock(),phase}));});assert.equal(result.code,25);assert.ok(!result.output.includes(token));assert.equal((await c.record()).status,'launching');c.advance(60001);await c.restart().worker();assert.equal((await c.record()).status,'launch_unknown');const files=await readdir(c.config.local.queue_directory);assert.equal(files.length,phase==='launching' ? 0:1);if(files.length){const file=join(c.config.local.queue_directory,files[0]);const entry=JSON.parse(await readFile(file,'utf8'));entry.state='running';entry.attempts=1;entry.task_started_at=entry.execution.created_at;await writeFile(file,JSON.stringify(entry));c.advance(60001);await c.restart().worker();assert.equal((await c.record()).status,'started');assert.equal((await readdir(c.config.local.queue_directory)).length,1);}});
