import test from 'node:test';
import assert from 'node:assert/strict';
import { createHmac,randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { mkdtemp,readFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { AcceptanceLedger } from '../dist/ledger.js';
import { FileStore } from '../dist/file-store.js';
import { HmacVerifier,strictJSON } from '../dist/hmac.js';
const token='fixture-run-token'.padEnd(43,'A');const shared=Buffer.from('fixture-shared-secret-32-bytes-long');const time=1800000000000;
const input=()=>({schema_version:1,site_id:'fixture-site',run_uuid:randomUUID(),callback_base:'https://wordpress.test/wp-json/odvr/v1/runner',runner_token:token});
const headers=(body,seconds=Math.floor(time/1000),secret=shared)=>['X-ODVR-Timestamp',String(seconds),'X-ODVR-Signature',createHmac('sha256',secret).update(String(seconds)+'\n').update(body).digest('hex')];
function verifier(){let reads=0;return {verifier:new HmacVerifier({'fixture-site':{callback_base:input().callback_base,shared_versions:['fixed'],rotation_until:null}},async()=>{reads++;return Buffer.from(shared);},()=>time),reads:()=>reads};}
async function store(t){const directory=await mkdtemp(join(tmpdir(),'odvr-ledger-'));t.after(()=>rm(directory,{recursive:true,force:true}));let now=time;return {directory,store:new FileStore(directory,()=>now),clock:()=>now,advance:ms=>{now+=ms;}};}
test('raw UTF-8 bytes・±300秒だけをHMAC認証する',async()=>{const {verifier:v}=verifier();const object=input();const body=Buffer.from(JSON.stringify(object));for(const seconds of [time/1000-300,time/1000,time/1000+300]){const accepted=await v.authenticate(object.site_id,body,headers(body,seconds));assert.equal(accepted.signedAt,seconds*1000);assert.deepEqual(v.payload(body,accepted.site),object);}for(const changed of [Buffer.from(body.toString().replace('fixture-site','fixture-Site')),Buffer.from(body.toString()+'\n')])await assert.rejects(v.authenticate(object.site_id,changed,headers(body)),{status:401});for(const seconds of [time/1000-301,time/1000+301])await assert.rejects(v.authenticate(object.site_id,body,headers(body,seconds)),{status:401});assert.ok(shared.every(byte=>byte!==0));});
test('重複認証header・未知site・別site秘密・不正timestampは副作用なし',async()=>{const {verifier:v,reads}=verifier();const body=Buffer.from(JSON.stringify(input()));for(const wrong of [[...headers(body),'X-ODVR-Timestamp',String(time/1000)],['X-ODVR-Timestamp','0'+String(time/1000),'X-ODVR-Signature','1'.repeat(64)],headers(body,time/1000,Buffer.alloc(32))])await assert.rejects(v.authenticate('fixture-site',body,wrong),{status:401});await assert.rejects(v.authenticate('unknown',body,headers(body)),{status:401});assert.equal(reads(),1);});
test('深い重複JSONキー・不正UTF-8・切断・深さ・サイズを拒否する',()=>{for(const body of ['{"site_id":"a","site_id":"b"}','{"site_id":"a","\\u0073ite_id":"b"}','{"a":{"x":1,"x":2}}','{"a":[{"x":1,"x":2}]}','{"a":1','[1]','null','{"x":'+ '['.repeat(11)+'0'+']'.repeat(11)+'}'])assert.throws(()=>strictJSON(Buffer.from(body)),{status:401});assert.throws(()=>strictJSON(Buffer.from([0xff,0xfe])),{status:401});assert.throws(()=>strictJSON(Buffer.alloc(16385)),{status:413});assert.deepEqual(strictJSON(Buffer.from('{"site_id":"日本語","x":[true,false,null,1e1]}')),{site_id:'日本語',x:[true,false,null,10]});});
test('署名済み登録外callback・未知Version・Token形式は400、診断にTokenを渡せない',async()=>{const {verifier:v}=verifier();const object=input();for(const wrong of [{...object,callback_base:'https://other.test/wp-json/odvr/v1/runner'},{...object,schema_version:2},{...object,runner_token:'short'}]){const body=Buffer.from(JSON.stringify(wrong));const accepted=await v.authenticate(wrong.site_id,body,headers(body));assert.throws(()=>v.payload(body,accepted.site),{status:400});}const diagnosis={schema_version:1,site_id:object.site_id,callback_base:object.callback_base};const body=Buffer.from(JSON.stringify(diagnosis));const accepted=await v.authenticate(diagnosis.site_id,body,headers(body));assert.deepEqual(v.payload(body,accepted.site,true),diagnosis);assert.throws(()=>v.payload(Buffer.from(JSON.stringify({...diagnosis,runner_token:token})),accepted.site,true),{status:400});});
test('rotationは固定2versionと最大10分の窓で検証する',async()=>{const old=Buffer.from('fixture-previous-shared-secret-32-byte');let now=time;const v=new HmacVerifier({'fixture-site':{callback_base:input().callback_base,shared_versions:['new','old'],rotation_until:time+600000}},async name=>Buffer.from(name==='new' ? shared:old),()=>now);const body=Buffer.from(JSON.stringify(input()));await v.authenticate('fixture-site',body,headers(body,time/1000,old));now+=600001;await assert.rejects(v.authenticate('fixture-site',body,headers(body,Math.floor(now/1000),old)),{status:401});await v.authenticate('fixture-site',body,headers(body,Math.floor(now/1000),shared));});
test('同時同一受付・digest衝突・restartは一つの永続記録を保つ',async t=>{const context=await store(t);const ledger=new AcceptanceLedger(context.store,context.clock);const object=input();const body=Buffer.from(JSON.stringify(object));const records=await Promise.all(Array.from({length:4},()=>ledger.reserve(object,body,time,'1','fixture@sha256:'+'1'.repeat(64))));assert.ok(records.every(record=>record.digest===records[0].digest));await assert.rejects(ledger.reserve(object,Buffer.from(body.toString()+'\n'),time,'1','fixture'),{status:409});const restarted=new AcceptanceLedger(new FileStore(context.directory,context.clock),context.clock);assert.deepEqual(await restarted.store.get(object.site_id,object.run_uuid),records[0]);const raw=await readFile(join(context.directory,'ledger.json'),'utf8');assert.ok(!raw.includes(token));assert.ok(!raw.includes(shared.toString()));assert.ok(!raw.includes('runner_token'));});
test('lease generationが古いworkerは状態を確定できず、期限を延長しない',async t=>{const context=await store(t);const ledger=new AcceptanceLedger(context.store,context.clock);const object=input();const record=await ledger.reserve(object,Buffer.from(JSON.stringify(object)),time,'1','fixture');const first=await ledger.acquire(record);assert.equal(await ledger.acquire(record),null);context.advance(60001);const second=await ledger.acquire(record);assert.equal(second.lease.generation,first.lease.generation+1);assert.equal(await ledger.patch(first,item=>{item.status='started';}),null);const patched=await ledger.patch(second,item=>{item.status='accepted';},true);assert.equal(patched.expires_at,record.expires_at);assert.equal(patched.next_action_at,context.clock()+60000);});
test('未終端2件と新規10件/分をtransactionで制限し、同じ再送を加算しない',async t=>{const context=await store(t);const ledger=new AcceptanceLedger(context.store,context.clock);const reserve=object=>ledger.reserve(object,Buffer.from(JSON.stringify(object)),time,'1','fixture');const first=input();await reserve(first);await reserve(input());await reserve(first);await assert.rejects(reserve(input()),{status:429});const left=await ledger.acquire(await context.store.get(first.site_id,first.run_uuid));await ledger.patch(left,item=>{item.active=false;item.status='failed';item.secret_deleted=true;},true);const record=await reserve(input());const leased=await ledger.acquire(record);await ledger.patch(leased,item=>{item.active=false;item.status='failed';item.secret_deleted=true;},true);
 // 別siteを使い、active slotを解放しながらminute上限を検証する。
 for(let i=0;i<10;i++){const object={...input(),site_id:'rate-site'};const record=await reserve(object);const lease=await ledger.acquire(record);await ledger.patch(lease,item=>{item.active=false;item.secret_deleted=true;item.status='failed';},true);}await assert.rejects(reserve({...input(),site_id:'rate-site'}),{status:429});});
test('独立3プロセスでも同じ受付を重複保存しない',async t=>{const {directory}=await store(t);const object=input();const body=Buffer.from(JSON.stringify(object));const children=await Promise.all(Array.from({length:3},()=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,['apps/dispatcher/tests/fixtures/reserve-worker.mjs'],{env:{...process.env,ODVR_FIXTURE_LEDGER:directory},stdio:['pipe','pipe','pipe']});let stdout='';let stderr='';child.stdout.on('data',data=>{stdout+=data;});child.stderr.on('data',data=>{stderr+=data;});child.on('error',reject);child.on('exit',code=>code===0 ? resolve(JSON.parse(stdout)):reject(new Error('独立fixtureの受付に失敗しました。')));child.stdin.end(JSON.stringify({body:body.toString('base64'),signed_at:Date.now()}));})));assert.equal(new Set(children.map(item=>item.digest)).size,1);const raw=await readFile(join(directory,'ledger.json'),'utf8');assert.equal(Object.keys(JSON.parse(raw).records).length,1);assert.ok(!raw.includes(token));});
