import test,{mock,after} from 'node:test';
import assert from 'node:assert/strict';
import { v2,protos } from '@google-cloud/run';
import { SecretManagerServiceClient } from '@google-cloud/secret-manager';
import { GrpcClient } from 'google-gax';
import { Firestore } from '@google-cloud/firestore';
import { context,token,shared } from './fixtures/context.mjs';
import { GoogleJobLauncher } from '../dist/google-jobs.js';
import { GoogleSecretStore,labels } from '../dist/google-secrets.js';
import { FirestoreStore } from '../dist/firestore-store.js';
import { crc32c } from '@odvr/runner/jobs/job-config';
// LRO clientのconstructorも通信stubまでfixtureに固定し、ADC/metadataへ接続しない。
const transport=mock.method(GrpcClient.prototype,'createStub',async()=>({close(){}}));after(()=>transport.mock.restore());
function patch(t,prototype,name,fn){const method=mock.method(prototype,name,fn);t.after(()=>method.mock.restore());return method;}
const options=input=>{assert.equal(input.timeout,5000);assert.equal(input.retry,null);};
async function record(c){return {...await c.ledger.reserve(c.input,c.body,c.clock(),'1',c.config.job.image),status:'launching',secret_step:'ready',secret_version:`projects/${c.config.secret_project}/secrets/odvr-run-${labels({site_id:c.input.site_id,run_uuid:c.input.run_uuid,digest:'a'.repeat(64)}).site_sha}-${c.input.run_uuid}/versions/1`,attempt_id:'1d2d58e9-6fda-4a5b-9957-6c0c49895d27'};}
function job(c){return {name:c.config.job.name,generation:'1',etag:'fixture-etag',reconciling:false,template:{taskCount:1,parallelism:1,template:{serviceAccount:c.config.job.runner_service_account,maxRetries:1,timeout:{seconds:'1800'},executionEnvironment:2,containers:[{name:c.config.job.container,image:c.config.job.image,command:['node','apps/runner/dist/job.js'],args:[],resources:{limits:{cpu:'2',memory:'2Gi'}}}]}}};}
function execution(c,launcher,r,suffix='execution'){return {name:c.config.job.name+'/executions/'+suffix,job:c.config.job.name,createTime:{seconds:Math.floor(r.created_at/1000)},taskCount:1,parallelism:1,runningCount:1,template:{serviceAccount:c.config.job.runner_service_account,containers:[{name:c.config.job.container,image:c.config.job.image,env:Object.entries(launcher.environment(r)).map(([name,value])=>({name,value}))}]}};}
test('Google Jobは固定構成・etagで一度だけ起動し、overrideに平文秘密や引数を渡さない',async t=>{const c=await context(t);const r=await record(c);let value=job(c);patch(t,v2.JobsClient.prototype,'getJob',async function(input,rpc){assert.equal(this.apiEndpoint,'run.googleapis.com');assert.deepEqual(input,{name:c.config.job.name});options(rpc);return [value];});let runs=0;patch(t,v2.JobsClient.prototype,'runJob',async function(input,rpc){options(rpc);runs++;assert.equal(input.name,c.config.job.name);assert.equal(input.etag,'fixture-etag');assert.equal(input.overrides.containerOverrides.length,1);assert.equal(input.overrides.containerOverrides[0].name,'runner');assert.equal(input.overrides.containerOverrides[0].env.length,6);assert.ok(!JSON.stringify(input).includes(token));assert.ok(!JSON.stringify(input).includes('args'));return [{name:c.config.job.name.split('/jobs/')[0]+'/operations/fixed'}];});patch(t,v2.JobsClient.prototype,'close',async()=>{});patch(t,v2.ExecutionsClient.prototype,'close',async()=>{});const launcher=new GoogleJobLauncher(c.config);assert.equal(await launcher.verify(r),true);assert.match(await launcher.launch(r),/operations\/fixed$/);assert.equal(runs,1);for(const mutate of [v=>v.generation='2',v=>v.template.taskCount=2,v=>v.template.parallelism=2,v=>v.template.template.maxRetries=2,v=>v.template.template.executionEnvironment=1,v=>v.template.template.containers[0].image='image:latest',v=>v.template.template.containers[0].args=['token'],v=>v.template.template.containers[0].command=['arbitrary'],v=>v.template.template.serviceAccount='other']){value=job(c);mutate(value);assert.equal(await launcher.verify(r),false);}await launcher.close();});
test('Operation protobuf・全ページExecution照合・Task終端を確認しscope混入を拒否する',async t=>{const c=await context(t);const r=await record(c);const launcher=new GoogleJobLauncher(c.config);const name=c.config.job.name.split('/jobs/')[0]+'/operations/fixed';let value=execution(c,launcher,r);let operation={name,done:false,metadata:{type_url:'type.googleapis.com/google.cloud.run.v2.Execution',value:protos.google.cloud.run.v2.Execution.encode(value).finish()}};patch(t,v2.JobsClient.prototype,'getOperation',async function(input,rpc){options(rpc);assert.equal(input.name,name);return [operation];});let pages=0;patch(t,v2.ExecutionsClient.prototype,'listExecutions',async function(input,rpc){options(rpc);assert.equal(rpc.autoPaginate,false);assert.equal(input.parent,c.config.job.name);pages++;return [[{name:value.name,createTime:value.createTime}],null,{nextPageToken:input.pageToken ? '':'page2'}];});patch(t,v2.ExecutionsClient.prototype,'getExecution',async(input,rpc)=>{options(rpc);assert.equal(input.name,value.name);return [value];});assert.equal((await launcher.operation(name)).execution.name,value.name);assert.equal((await launcher.operation(name)).execution.terminal,false);assert.equal((await launcher.candidates(r)).length,2);assert.equal(pages,2);value={...value,completionTime:{seconds:r.created_at/1000+1},runningCount:0,failedCount:1};assert.equal((await launcher.execution(value.name)).terminal,true);value={...value,reconciling:true};assert.equal((await launcher.execution(value.name)).terminal,false);operation={name,done:true,error:{code:7}};assert.equal((await launcher.operation(name)).failed,true);operation={name,done:true,error:{code:13}};assert.equal((await launcher.operation(name)).failed,false);await assert.rejects(launcher.operation(name.replace('/locations/asia-northeast1/','/locations/us-central1/')),{code:'odvr_operation_mismatch'});value={...value,template:{...value.template,serviceAccount:'other'}};await assert.rejects(launcher.execution(value.name),{code:'odvr_execution_mismatch'});});
test('Secretは元の署名期限・所有labels・一度のversion追加・CRCと条件付きIAMを使う',async t=>{const c=await context(t);const r=await record(c);const store=new GoogleSecretStore(c.config);const name=store.name(r);let data;let policy;patch(t,SecretManagerServiceClient.prototype,'createSecret',async function(input,rpc){assert.equal(this.apiEndpoint,'secretmanager.googleapis.com');options(rpc);assert.equal(input.parent,'projects/'+c.config.secret_project);assert.equal(input.secret.expireTime.seconds,r.expires_at/1000);assert.deepEqual(input.secret.labels,labels(r));return [{name}];});patch(t,SecretManagerServiceClient.prototype,'getSecret',async(input,rpc)=>{options(rpc);assert.equal(input.name,name);return [{name,expireTime:{seconds:r.expires_at/1000},labels:labels(r)}];});patch(t,SecretManagerServiceClient.prototype,'addSecretVersion',async(input,rpc)=>{options(rpc);assert.equal(input.parent,name);assert.equal(input.payload.data.toString(),token);assert.equal(input.payload.dataCrc32c,crc32c(input.payload.data));data=input.payload.data;return [{name:name+'/versions/1'}];});patch(t,SecretManagerServiceClient.prototype,'listSecretVersions',async(input,rpc)=>{options(rpc);assert.equal(rpc.autoPaginate,false);assert.equal(input.parent,name);return [[{name:name+'/versions/1',state:1}],null,{}];});patch(t,SecretManagerServiceClient.prototype,'getIamPolicy',async(input,rpc)=>{options(rpc);assert.equal(input.resource,name);assert.equal(input.options.requestedPolicyVersion,3);return [{etag:Buffer.from('etag'),bindings:[]}];});patch(t,SecretManagerServiceClient.prototype,'setIamPolicy',async(input,rpc)=>{options(rpc);policy=input.policy;return [policy];});let deletes=0;patch(t,SecretManagerServiceClient.prototype,'deleteSecret',async(input,rpc)=>{options(rpc);assert.equal(input.name,name);deletes++;});patch(t,SecretManagerServiceClient.prototype,'close',async()=>{});await store.create(r);assert.equal(await store.add(r,token),r.secret_version);assert.ok(data.every(byte=>byte===0));await store.grant(r);assert.equal(policy.version,3);assert.deepEqual(policy.bindings[0].members,['serviceAccount:'+c.config.job.runner_service_account]);assert.equal(policy.bindings[0].condition.expression,`request.time < timestamp("${new Date(r.expires_at).toISOString()}")`);await assert.rejects(store.remove({...r,digest:'f'.repeat(64)}),{code:'odvr_secret_ownership_conflict'});await store.remove(r);assert.equal(deletes,1);await store.close();});
test('Dispatcherは登録済みHMAC鍵だけを読み、Run秘密payloadは読まない',async t=>{const c=await context(t);const store=new GoogleSecretStore(c.config);const resource=c.config.sites[c.input.site_id].shared_versions[0];let bad=false;let calls=0;patch(t,SecretManagerServiceClient.prototype,'accessSecretVersion',async(input,rpc)=>{options(rpc);assert.equal(input.name,resource);calls++;return [{name:resource,payload:{data:Buffer.from(shared),dataCrc32c:String(crc32c(shared)+(bad ? 1:0))}}];});assert.deepEqual(await store.shared(resource),shared);await assert.rejects(store.shared('projects/222222222222/secrets/arbitrary/versions/1'));assert.equal(calls,1);bad=true;await assert.rejects(store.shared(resource));});
test('Firestore adapterはRunとsite counterを同じtransactionで確定し、due queueだけを読む',async t=>{const c=await context(t);const values=new Map();let txs=0;const collections=[];patch(t,Firestore.prototype,'collection',function(name){collections.push(name);const query={where(field,op,time){assert.equal(field,'next_action_at');assert.equal(op,'<=');assert.equal(time,c.clock());return this;},orderBy(field){assert.equal(field,'next_action_at');return this;},limit(n){assert.equal(n,25);return this;},async get(){return {docs:[...values.entries()].filter(([key])=>key.startsWith('odvr_acceptance/')).map(([,value])=>({data:()=>value}))};},doc(id){const path=name+'/'+id;return {path,async get(){return {exists:values.has(path),data:()=>values.get(path)};}};}};return query;});patch(t,Firestore.prototype,'runTransaction',async(fn,options)=>{txs++;assert.equal(options.maxAttempts,5);return fn({getAll:async(...refs)=>{assert.equal(refs.length,2);return refs.map(ref=>({exists:values.has(ref.path),data:()=>values.get(ref.path)}));},set:(ref,value)=>values.set(ref.path,structuredClone(value)),delete:ref=>values.delete(ref.path)});});patch(t,Firestore.prototype,'terminate',async()=>{});const store=new FirestoreStore(c.config.firestore.project,'(default)',undefined,c.clock);const ledger=new c.ledger.constructor(store,c.clock);const first=await ledger.reserve(c.input,c.body,c.clock(),'1',c.config.job.image);const second=await ledger.reserve(c.input,c.body,c.clock()+1000,'1',c.config.job.image);assert.equal(first.expires_at,second.expires_at);assert.equal(txs,2);assert.equal((await store.scan(null,25)).records.length,1);assert.ok(collections.includes('odvr_sites'));assert.ok(!JSON.stringify([...values.values()]).includes(token));await store.close();});
test('起動POSTの通信不明は自動再送せず、確実な権限拒否だけ区別する',async t=>{const c=await context(t);const r=await record(c);patch(t,v2.JobsClient.prototype,'getJob',async()=>[job(c)]);let code=14;let calls=0;patch(t,v2.JobsClient.prototype,'runJob',async(_input,rpc)=>{options(rpc);calls++;throw Object.assign(new Error('fixture lost'),{code});});const launcher=new GoogleJobLauncher(c.config);await launcher.verify(r);await assert.rejects(launcher.launch(r),{code:14});assert.equal(calls,1);code=7;await assert.rejects(launcher.launch(r),{name:'Error',message:'Jobの起動を受け付けられませんでした。'});assert.equal(calls,2);});
test('孤立Secretは専用project・所有権・期限を再確認し、一覧後の所有者変更を削除しない',async t=>{const c=await context(t);const r=await record(c);const store=new GoogleSecretStore(c.config);const expired={name:store.name(r),expires_at:Math.floor(Date.now()/1000)*1000-1000,labels:labels(r)};let owner='dispatcher-v1';let deleted=0;patch(t,SecretManagerServiceClient.prototype,'listSecrets',async(input,rpc)=>{options(rpc);assert.equal(input.parent,'projects/'+c.config.secret_project);assert.equal(input.filter,'labels.odvr_owner=dispatcher-v1');assert.equal(rpc.autoPaginate,false);return [[{name:expired.name,expireTime:{seconds:expired.expires_at/1000},labels:expired.labels}],null,{nextPageToken:'next'}];});patch(t,SecretManagerServiceClient.prototype,'getSecret',async input=>{assert.equal(input.name,expired.name);return [{name:expired.name,expireTime:{seconds:expired.expires_at/1000},labels:{...expired.labels,odvr_owner:owner}}];});patch(t,SecretManagerServiceClient.prototype,'deleteSecret',async input=>{assert.equal(input.name,expired.name);deleted++;});const page=await store.orphans(null,25);assert.equal(page.cursor,'next');owner='another';await assert.rejects(store.removeOrphan(page.secrets[0]),{code:'odvr_secret_ownership_conflict'});assert.equal(deleted,0);owner='dispatcher-v1';await store.removeOrphan(page.secrets[0]);assert.equal(deleted,1);await assert.rejects(store.removeOrphan({...expired,expires_at:Date.now()+60000}));assert.equal(deleted,1);});
