import test,{mock} from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { createHmac } from 'node:crypto';
import { writeFile,readdir } from 'node:fs/promises';
import { OAuth2Client } from 'google-auth-library';
import { context,token,shared } from './fixtures/context.mjs';
import { checkedConfig } from '../dist/config.js';
import { createDispatcherServer } from '../dist/server.js';
import { HmacVerifier } from '../dist/hmac.js';
import { WorkerAuth } from '../dist/worker-auth.js';
function signature(c,body){const timestamp=String(c.clock()/1000);return {'X-ODVR-Timestamp':timestamp,'X-ODVR-Signature':createHmac('sha256',shared).update(timestamp+'\n').update(body).digest('hex')};}
async function setup(t){const c=await context(t);let probes=0;const logs=[];const auth=new WorkerAuth(c.config);await writeFile(c.config.local.worker_key_file,'W'.repeat(43),{mode:0o600});const server=createDispatcherServer({engine:c.engine,verifier:new HmacVerifier(c.config.sites,async()=>Buffer.from(shared),c.clock),workerAuth:headers=>auth.authenticate(headers),probe:async()=>{probes++;return true;},clock:c.clock,log:entry=>logs.push(entry)});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>{server.close(resolve);server.closeAllConnections();}));const request=(method,path,body=Buffer.alloc(0),headers=signature(c,body))=>new Promise((resolve,reject)=>{const req=http.request({hostname:'127.0.0.1',port:server.address().port,method,path,headers:{'Content-Type':'application/json','Content-Length':String(body.length),...headers}},res=>{let text='';res.on('data',chunk=>{text+=chunk;});res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:JSON.parse(text)}));});req.on('error',reject);req.end(body);});return {...c,request,logs,probes:()=>probes};}
test('HTTP受付・署名付きGET・同一再送は同じExecutionを返す',async t=>{const c=await setup(t);const response=await c.request('POST','/v1/jobs',c.body);assert.equal(response.status,200);assert.equal(response.headers['cache-control'],'no-store');const lookup=await c.request('GET','/v1/jobs/'+c.input.run_uuid+'?site_id=fixture-site');assert.deepEqual(lookup.body,response.body);assert.equal((await c.request('POST','/v1/jobs',c.body)).body.runner_execution_id,response.body.runner_execution_id);assert.ok(!JSON.stringify(c.logs).includes(token));});
test('署名なし・重複JSON・callback変更・サイズ・圧縮・重複queryを安全に拒否する',async t=>{const c=await setup(t);for(const [method,path,body,headers,status] of [['POST','/v1/jobs',c.body,{},401],['POST','/v1/jobs',Buffer.from('{"site_id":"fixture-site","site_id":"other"}'),undefined,401],['POST','/v1/jobs',Buffer.from(JSON.stringify({...c.input,callback_base:'https://other.test/wp-json/odvr/v1/runner'})),undefined,400],['POST','/v1/jobs',Buffer.alloc(16385),undefined,413],['POST','/v1/jobs',c.body,{'Content-Encoding':'gzip'},400],['GET','/v1/jobs/'+c.input.run_uuid+'?site_id=fixture-site&site_id=fixture-site',Buffer.alloc(0),undefined,400]]){const result=await c.request(method,path,body,headers ?? signature(c,body));assert.equal(result.status,status);assert.ok(!JSON.stringify(result.body).includes(token));}assert.equal(await c.record(),null);});
test('診断は台帳health・Job確認・callbackだけでRun/Secret/Jobを作らない',async t=>{const c=await setup(t);const body=Buffer.from(JSON.stringify({schema_version:1,site_id:c.input.site_id,callback_base:c.input.callback_base}));const result=await c.request('POST','/v1/connection-test',body);assert.equal(result.status,200);assert.equal(result.body.item.checks.dispatcher,'passed');assert.equal(c.probes(),1);assert.equal(await c.record(),null);assert.equal((await readdir(c.config.local.run_directory)).length,0);c.engine.dependencies.jobs.verify=async()=>{throw new Error('Bearer '+token);};assert.equal((await c.request('POST','/v1/connection-test',body)).body.item.checks.dispatcher,'failed');assert.ok(!JSON.stringify(c.logs).includes(token));});
test('内部workerは別認証を要求し、外部HMACでは動かない',async t=>{const c=await setup(t);assert.equal((await c.request('POST','/internal/reconcile')).status,401);assert.equal((await c.request('POST','/internal/reconcile',Buffer.alloc(0),{Authorization:'Bearer '+'W'.repeat(43)})).status,200);assert.equal((await c.request('POST','/internal/reconcile',Buffer.from('{}'),{Authorization:'Bearer '+'W'.repeat(43)})).status,400);});
test('SDK例外の原文・Token・秘密参照をHTTPやログへ出さない',async t=>{const c=await setup(t);c.engine.dependencies.secrets.create=async()=>{throw new Error(token+' projects/private/secrets/private');};const result=await c.request('POST','/v1/jobs',c.body);assert.equal(result.status,503);assert.equal(result.body.data.retryable,true);for(const value of [result.body,c.logs]){assert.ok(!JSON.stringify(value).includes(token));assert.ok(!JSON.stringify(value).includes('projects/private'));}});
test('設定は固定登録・HTTPS・digest・project・scheduler・local境界を検証する',async t=>{const c=await context(t);assert.deepEqual(checkedConfig(c.config,{},c.clock()),c.config);const cloud={...c.config,profile:'cloud',job:{...c.config.job,usage_profile:'update_test'}};delete cloud.local;assert.equal(checkedConfig(cloud,{},c.clock()).profile,'cloud');for(const value of [{...cloud,job:{...cloud.job,usage_profile:undefined}},{...cloud,job:{...cloud.job,usage_profile:'unknown'}},{...cloud,local:c.config.local},{...cloud,sites:{...cloud.sites,extra:{...c.config.sites['fixture-site'],callback_base:'http://wordpress.test/wp-json/odvr/v1/runner'}}},{...cloud,job:{...cloud.job,image:'image:latest'}},{...cloud,scheduler:{...cloud.scheduler,audience:'https://user:pass@dispatcher.test/internal/reconcile'}},{...c.config,local:{...c.config.local,run_directory:'relative'}},{...c.config,local:{...c.config.local,firestore:{host:'metadata.google.internal',port:8085}}}])assert.throws(()=>checkedConfig(value,{},c.clock()));for(const environment of [{FIRESTORE_EMULATOR_HOST:'127.0.0.1:8085'},{GOOGLE_APPLICATION_CREDENTIALS:'private'},{NODE_DEBUG:'http'}]){assert.throws(()=>checkedConfig(cloud,environment,c.clock()));assert.throws(()=>checkedConfig(c.config,environment,c.clock()));}});
test('worker OIDCは署名検証後にもaudience・sub・email・issuerを固定する',async t=>{const c=await context(t);const cloud={...c.config,profile:'cloud'};delete cloud.local;const auth=new WorkerAuth(cloud);let payload={iss:'https://accounts.google.com',sub:cloud.scheduler.subject,email:cloud.scheduler.email,email_verified:true,aud:cloud.scheduler.audience};const verify=mock.method(OAuth2Client.prototype,'verifyIdToken',async input=>{assert.equal(input.audience,cloud.scheduler.audience);return {getPayload:()=>payload};});t.after(()=>verify.mock.restore());assert.equal(await auth.authenticate(['Authorization','Bearer '+'x'.repeat(43)]),true);for(const changes of [{sub:'different'},{email:'different'},{email_verified:false},{aud:'different'},{iss:'https://attacker.test'}]){const original=payload;payload={...original,...changes};assert.equal(await auth.authenticate(['Authorization','Bearer '+'x'.repeat(43)]),false);payload=original;}assert.equal(await auth.authenticate(['Authorization','Bearer '+'x'.repeat(43),'Authorization','Bearer '+'x'.repeat(43)]),false);});
