import { createHash } from 'node:crypto';
import { runSecretName } from './job-config.js';
export interface LocalEntry {storage_version:1;operation:string;execution:{name:string;created_at:number;terminal:boolean;image:string;environment:Record<string,string>};state:'queued'|'running'|'terminal';attempts:number;job_generation:string;task_started_at:number|null}
export interface LocalQueueRegistration {job:{name:string;image:string;generation:string};secret_project:string;sites:Record<string,{callback_base:string}>}
export function queueFilename(operation:string):string{return createHash('sha256').update(operation).digest('hex')+'.json';}
/** LauncherとDispatcherで同じ固定メタデータを検証する。値からcommandや任意envを作らない。 */
export function checkedLocalEntry(value:unknown,registration:LocalQueueRegistration,filename:string,allowTerminalHistory=false):LocalEntry {
 try{const entry=value as LocalEntry;const execution=entry.execution;const environment=execution.environment;
  // 終了済み履歴だけは前の固定digestを照合できる。実行候補の設定は変更しない。
  if(allowTerminalHistory && entry.state==='terminal' && /^odvr\/runner@sha256:[a-f0-9]{64}$/.test(execution.image) && /^[1-9][0-9]*$/.test(entry.job_generation))registration={...registration,job:{...registration.job,image:execution.image,generation:entry.job_generation}};const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/;
  if(Object.keys(entry).sort().join()!=='attempts,execution,job_generation,operation,state,storage_version,task_started_at' || entry.storage_version!==1 || !['queued','running','terminal'].includes(entry.state) || !Number.isInteger(entry.attempts) || entry.attempts<0 || entry.attempts>2 || (entry.state==='queued' ? entry.attempts!==0:entry.attempts===0) || entry.job_generation!==registration.job.generation || Object.keys(execution).sort().join()!=='created_at,environment,image,name,terminal' || !Number.isSafeInteger(execution.created_at) || execution.created_at<0 || execution.terminal!==(entry.state==='terminal') || execution.image!==registration.job.image || Object.keys(environment).sort().join()!=='ODVR_ATTEMPT_ID,ODVR_CALLBACK_BASE,ODVR_RUN_SECRET_VERSION,ODVR_RUN_UUID,ODVR_SITE_ID,ODVR_TOKEN_EXPIRES_AT' || !Object.values(environment).every(item=>typeof item==='string' && item.length<=2048) || !/^[A-Za-z0-9_-]{1,100}$/.test(environment.ODVR_SITE_ID) || !uuid.test(environment.ODVR_RUN_UUID) || !uuid.test(environment.ODVR_ATTEMPT_ID) || !Object.hasOwn(registration.sites,environment.ODVR_SITE_ID) || environment.ODVR_CALLBACK_BASE!==registration.sites[environment.ODVR_SITE_ID].callback_base || environment.ODVR_RUN_SECRET_VERSION!==`projects/${registration.secret_project}/secrets/${runSecretName(environment.ODVR_SITE_ID,environment.ODVR_RUN_UUID)}/versions/1` || new Date(environment.ODVR_TOKEN_EXPIRES_AT).toISOString()!==environment.ODVR_TOKEN_EXPIRES_AT || entry.operation!==registration.job.name.split('/jobs/')[0]+'/operations/'+environment.ODVR_ATTEMPT_ID || execution.name!==registration.job.name+'/executions/local-'+environment.ODVR_ATTEMPT_ID || queueFilename(entry.operation)!==filename || (entry.state==='queued' ? entry.task_started_at!==null:!Number.isSafeInteger(entry.task_started_at)))throw new Error();
  return structuredClone(entry);
 }catch{throw new Error('local実行記録を確認してください。');}
}
