import { spawn } from 'node:child_process';
import { mkdir,readFile,writeFile,chmod,rm } from 'node:fs/promises';
import { resolve,join } from 'node:path';
import { setTimeout as wait } from 'node:timers/promises';
import { createHash } from 'node:crypto';
const root=resolve('.odvr-local');const input=join(root,'input');const stateFile=join(root,'state.json');
const phase=process.argv[2];if(!['start','fixture','status','stop','check'].includes(phase))throw new Error('local操作を指定してください。');
async function command(args,body,environment=process.env){return new Promise((done,reject)=>{let stdout='';let stderr='';const child=spawn(args[0],args.slice(1),{env:environment,stdio:['pipe','pipe','pipe']});child.stdout.on('data',chunk=>{stdout+=chunk;});child.stderr.on('data',chunk=>{stderr+=chunk;});child.on('error',reject);child.on('exit',code=>code===0 ? done(stdout):reject(new Error('local操作に失敗しました。 '+args[0]+' '+args.slice(1,3).join(' ')+' '+stderr.replace(/[A-Za-z0-9_-]{43,}/g,'[省略]').slice(-1500))));child.stdin.end(body);});}
async function saved(){return JSON.parse(await readFile(stateFile,'utf8'));}async function save(state){await writeFile(stateFile,JSON.stringify(state,null,2)+'\n',{mode:0o600});}
const images=JSON.parse(await readFile(join(root,'images.json'),'utf8'));for(const component of ['runner','dispatcher'])if(!new RegExp('^odvr/'+component+'@sha256:[a-f0-9]{64}$').test(images.images[component]))throw new Error('Image digestを確認してください。');
const environment={...process.env,ODVR_RUNNER_IMAGE:images.images.runner,ODVR_DISPATCHER_IMAGE:images.images.dispatcher,ODVR_LOCAL_INPUT:input};
const compose=(...args)=>command(['docker','compose','--profile','local',...args],undefined,environment);
const wp=(state,...args)=>command(['docker','exec','--user','33:33',state.cli,'wp','--path=/var/www/html',...args]);
async function copyBytes(container,path,bytes,mode='600'){await command(['docker','exec','-i','--user','0:0',container,'php','-r',"umask(0077); $file=fopen($argv[1], 'xb'); if(false===$file)exit(1); $data=stream_get_contents(STDIN); if(fwrite($file,$data)!==strlen($data))exit(1); fclose($file); chmod($argv[1],octdec($argv[2])); chown($argv[1],33); chgrp($argv[1],33);",path,mode],bytes);}
async function fixture(state,action){return wp(state,'eval-file','/tmp/odvr-local-fixture.php',action);}
try{
 if(phase==='start'){
  await mkdir(input,{recursive:true,mode:0o700});try{await saved();throw new Error('先にlocal:stopで前回の環境を復元してください。');}catch(error){if(error.code!=='ENOENT')throw error;}
  const containers=(await command(['docker','ps','--format','{{.Names}}'])).trim().split('\n');const wordpress=containers.filter(name=>/^wp-env-[a-z0-9-]+-wordpress-1$/.test(name) && !name.endsWith('-tests-wordpress-1') && name.includes('od-visual-regression'));if(wordpress.length!==1)throw new Error('このrepositoryの既存wp-envを一つ起動してください。');const cli=wordpress[0].replace(/-wordpress-1$/,'-cli-1');if(!containers.includes(cli))throw new Error('wp-env CLIが見つかりません。');
  const state={wordpress:wordpress[0],cli,connected:[],fixture:false,configured:false};for(const container of [state.wordpress,state.cli])await command(['docker','exec',container,'sh','-c','test ! -e /tmp/odvr-fixture-shared && test ! -e /tmp/odvr-fixture-ca.pem && test ! -e /tmp/odvr-local-fixture.php && test ! -e /tmp/odvr-local-fixture-state.json && test ! -e /tmp/odvr-local-wp-config-before']);state.config_metadata=(await command(['docker','exec',state.wordpress,'stat','-c','%u:%g:%a','/var/www/html/wp-config.php'])).trim();if(!/^[0-9]+:[0-9]+:[0-7]{3,4}$/.test(state.config_metadata))throw new Error('元のwp-config属性を確認してください。');await command(['docker','exec',state.wordpress,'sh','-c','test ! -e /var/www/html/wp-content/mu-plugins/odvr-local-fixture.php && test ! -e /etc/apache2/conf-enabled/odvr-local-fixture.conf']);await wp(state,'eval',"if (defined('ODVR_HTTP_AUTH_USER') || defined('ODVR_HTTP_AUTH_PASSWORD') || defined('ODVR_HTTP_AUTH_ORIGIN')) { WP_CLI::error('既存のBasic設定がある環境ではlocal fixtureを実行できません。'); }");await save(state);
  let network;try{network=JSON.parse(await command(['docker','network','inspect','odvr-local-wordpress']))[0];}catch{await command(['docker','network','create','--subnet','172.30.238.0/24','odvr-local-wordpress']);network=JSON.parse(await command(['docker','network','inspect','odvr-local-wordpress']))[0];}if(network.IPAM.Config.length!==1 || network.IPAM.Config[0].Subnet!=='172.30.238.0/24')throw new Error('専用bridgeを固定できない環境は非対応です。');
  for(const [container,address] of [[state.wordpress,'172.30.238.10'],[state.cli,'172.30.238.11']]){await command(['docker','network','connect','--ip',address,'odvr-local-wordpress',container]);state.connected.push(container);await save(state);}
  const base='https://wordpress.fixture.test:8443';const shared='projects/111111111111/secrets/local-shared/versions/1';const sites={'local-fixture':{callback_base:base+'/wp-json/odvr/v1/runner'}};const destination={origin:base,address:'172.30.238.20',port:8443};const job={name:'projects/odvr-local/locations/asia-northeast1/jobs/odvr-runner',container:'runner',image:images.images.runner,generation:'1',runner_service_account:'runner-sa@odvr-local.iam.gserviceaccount.com'};
  const dispatcher={schema_version:1,profile:'local',sites:{'local-fixture':{...sites['local-fixture'],shared_versions:[shared],rotation_until:null}},firestore:{project:'odvr-local',database:'(default)'},secret_project:'222222222222',job,scheduler:{audience:'https://dispatcher.fixture.test:8443/internal/reconcile',subject:'123456789012345678',email:'worker-sa@odvr-local.iam.gserviceaccount.com'},local:{callback_destination:destination,firestore:{host:'firestore',port:8085},shared_directory:'/run/odvr/secrets/shared',run_directory:'/run/odvr/secrets/runs',queue_directory:'/run/odvr/queue',worker_key_file:'/run/odvr/secrets/worker-key'}};
  const runner={schema_version:1,profile:'local',sites,local_destination:destination,local_secret_directory:'/run/odvr/secrets/runs'};
  const launcher={job:{name:job.name,image:job.image,generation:job.generation},secret_project:dispatcher.secret_project,sites};
  for(const [file,value] of [['dispatcher.json',dispatcher],['runner.json',runner],['launcher.json',launcher],['relay.json',{wordpress:'http://172.30.238.10:80',dispatcher:'http://dispatcher:8080'}]])await writeFile(join(input,file),JSON.stringify(value,null,2)+'\n',{mode:0o600});
  await command(['openssl','req','-x509','-newkey','rsa:2048','-nodes','-days','7','-keyout',join(input,'fixture-key.pem'),'-out',join(input,'fixture-ca.pem'),'-subj','/CN=ODVR local fixture','-addext','subjectAltName=DNS:wordpress.fixture.test,DNS:dispatcher.fixture.test']);await chmod(join(input,'fixture-key.pem'),0o600);
  await compose('up','-d');const key=await command(['docker','compose','--profile','local','exec','-T','dispatcher','node','-e',"process.stdout.write(require('fs').readFileSync('/run/odvr/secrets/shared/"+createHash('sha256').update(shared).digest('hex')+"'))"],undefined,environment);if(!/^fixture-only-[A-Za-z0-9_-]{43}$/.test(key))throw new Error('fixture秘密の初期化を確認してください。');
  for(const container of [state.wordpress,state.cli]){await copyBytes(container,'/tmp/odvr-fixture-shared',key);await copyBytes(container,'/tmp/odvr-fixture-ca.pem',await readFile(join(input,'fixture-ca.pem')),'644');}
  await command(['docker','exec',state.wordpress,'sh','-c','test ! -e /tmp/odvr-local-wp-config-before && cp /var/www/html/wp-config.php /tmp/odvr-local-wp-config-before && chmod 600 /tmp/odvr-local-wp-config-before']);state.configured=true;await save(state);await command(['docker','exec',state.wordpress,'chown','33:33','/var/www/html/wp-config.php']);await command(['docker','exec',state.wordpress,'chmod','640','/var/www/html/wp-config.php']);
  for(const [name,value,raw] of [['ODVR_LOCAL_FIXTURE','true',true],['ODVR_STORAGE_PROTECTION_VERIFIED','true',true],['ODVR_DISPATCHER_URL','https://dispatcher.fixture.test:8443',false],['ODVR_DISPATCHER_SHARED_SECRET',"file_get_contents('/tmp/odvr-fixture-shared')",true],['WP_HOME',base,false],['WP_SITEURL',base,false],['WP_DEBUG_LOG','false',true]])await wp(state,'config','set',name,value,...(raw ? ['--raw']:[]));
  await command(['docker','exec',state.wordpress,'sh','-c','mkdir -p /var/www/html/wp-content/mu-plugins && test ! -e /var/www/html/wp-content/mu-plugins/odvr-local-fixture.php && test ! -e /etc/apache2/conf-enabled/odvr-local-fixture.conf']);
  await copyBytes(state.wordpress,'/var/www/html/wp-content/mu-plugins/odvr-local-fixture.php',await readFile('infra/local/wp-mu.php'),'644');await copyBytes(state.wordpress,'/etc/apache2/conf-enabled/odvr-local-fixture.conf',await readFile('infra/local/wp-apache.conf'),'644');await copyBytes(state.cli,'/tmp/odvr-local-fixture.php',await readFile('infra/local/wp-fixture.php'),'644');
  await command(['docker','exec',state.wordpress,'php','-l','/var/www/html/wp-content/mu-plugins/odvr-local-fixture.php']);await command(['docker','exec',state.cli,'php','-l','/tmp/odvr-local-fixture.php']);
  await command(['docker','exec',state.wordpress,'sh','-c','a2enmod headers >/dev/null && apachectl -t && apachectl -k graceful']);
  state.ready=true;await save(state);process.stdout.write('固定HTTPS bridge・両Image・emulator・tmpfs・launcher・workerを起動しました。\n');
 }else if(phase==='fixture'){
  const state=await saved();if(!state.ready)throw new Error('local起動を完了してからfixtureを実行してください。');state.fixture=true;await save(state);const result=await fixture(state,'setup');process.stdout.write(result);
 }else if(phase==='status')process.stdout.write(await fixture(await saved(),'status'));
 else if(phase==='check'){await compose('config','--quiet');process.stdout.write('composeの固定設定を確認しました。\n');}
 else{
  const state=await saved();if(state.fixture)process.stdout.write(await fixture(state,'cleanup'));
  await compose('down');if(state.configured){await command(['docker','exec',state.wordpress,'sh','-c','cp /tmp/odvr-local-wp-config-before /var/www/html/wp-config.php && rm -f /tmp/odvr-local-wp-config-before /var/www/html/wp-content/mu-plugins/odvr-local-fixture.php /etc/apache2/conf-enabled/odvr-local-fixture.conf && apachectl -k graceful']);if(state.config_metadata){if(!/^[0-9]+:[0-9]+:[0-7]{3,4}$/.test(state.config_metadata))throw new Error('復元属性を確認してください。');const [uid,gid,mode]=state.config_metadata.split(':');await command(['docker','exec',state.wordpress,'chown',uid+':'+gid,'/var/www/html/wp-config.php']);await command(['docker','exec',state.wordpress,'chmod',mode,'/var/www/html/wp-config.php']);}}
  for(const container of [state.wordpress,state.cli])await command(['docker','exec','--user','0:0',container,'rm','-f','/tmp/odvr-fixture-shared','/tmp/odvr-fixture-ca.pem','/tmp/odvr-local-fixture.php']);for(const container of state.connected)await command(['docker','network','disconnect','odvr-local-wordpress',container]);await rm(join(input,'fixture-key.pem'),{force:true});await rm(join(input,'fixture-ca.pem'),{force:true});await rm(stateFile);process.stdout.write('localを停止し、既存wp-envの設定とfixtureを復元しました。\n');
 }
}catch(error){process.stderr.write(error.message+'\n');process.exitCode=1;}
